[package]
name = "deckrypt"
version = "0.1.0"
edition = "2021"
links = "keymap"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
evdev = "0.12.2"
libc = "0.2.158"
sudo = "0.6.0"
toml = "0.8.19"

[build-dependencies]
cc = "1.0"
