# Black Shark Green Ghost Gamepad

[buttons]
BTN_MODE = 'ENTER'
BTN_SOUTH = 'a'
BTN_NORTH = 'x'
BTN_WEST = 'y'
BTN_EAST = 'b'

[alternate_buttons]
BTN_SOUTH = 'z'
BTN_NORTH = 'c'
BTN_WEST = 'd'
BTN_EAST = 'w'

[axes]
ABS_X = { negative = 'e', positive = 'f' }
ABS_Y = { negative = 'g', positive = 'h' }

[alternate_axes]
ABS_X = { negative = 'i', positive = 'j' }
ABS_Y = { negative = 'k', positive = 'l' }

[modifiers]
shift_key = "BTN_TL"
alternate_key = "BTN_TR"

[friendly_names]
BTN_SOUTH = "A"
BTN_NORTH = "X"
BTN_WEST = "Y"
BTN_EAST = "B"
BTN_TL = "LT"
BTN_TR = "RT"
ABS_X_NEG = "LS_L"
ABS_X_POS = "LS_R"
ABS_Y_NEG = "LS_U"
ABS_Y_POS = "LS_D
